//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace auth.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        public int Id { get; set; }

        [DisplayName("Product Name")]
        public string product_name { get; set; }

        [DisplayName("Category Name")]
        public string category_name { get; set; }


        [DisplayName("Price")]
        public Nullable<double> price { get; set; }


        [DisplayName("Quantity")]
        public int quantity { get; set; }


        [DisplayName("Small Description")]
        public string sdes { get; set; }


        [DisplayName("Large Description")]
        public  string ldes { get; set; }


        [DisplayName("Small Image")]
        public string simg { get; set; }


        [DisplayName("Large Image")]
        public string limg { get; set; }
    }
}
